apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudshield-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraudshield-app
  template:
    metadata:
      labels:
        app: fraudshield-app
    spec:
      containers:
      - name: fraudshield-app
        image: fraudshield-app:1.0
        ports:
        - containerPort: 5000