apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraudshield-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/FraudShield.git
    path: kubernetes
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true